Kevin Zhang

1. What are the two most common supervised tasks? Logistic regression and classification Are the two most common supervised tasks. 

2. What are four common unsupervised tasks? Clustering, visualization, dimensionality reduction, and Association rule learning. 

3. What is the difference between a model parameter and a learning algorithm’s hyperparameter? A model parameter is meant to serve as a characteristic of a model in which it's possible to define certain systems within that model while a hyperparameter is a parameter that is specifically meant to deal with a learning algorithm. So therefore, while both are technically parameters, a model parameter specifically deals with models, while a hyperparameter deals with a learning algorithm.

4. What is a test set, and why would you want to use it? A test set is a set that is used to test the performance of a model. We would want to use the test set if we want to evaluate the performance of a model and also if we want to find out the generalization error. That way, we can get a good sense of how the model would perform if we use it on a real data set.  

5. What is the purpose of a validation set? A validation set is the part of the training set that is held out to evaluate candidate models in an attempt to find the best one. When a person is trying to find the best model to use, they first test the models on a reduced training set, which is basically the full training set minus the validation set. Next, they test the models on the validation set to produce the best candidates. Finally, they test the models on the full training set to produce the best model to use. 



6. What can go wrong if you tune hyperparameters using the test set? If you tune hyperparameters using the data set, you run the risk of choosing a model that is the best candidate for the test set, but not good for practical use in the real world. By choosing only the best candidate model for that particular test set, you are effectively ignoring how well the model would perform if it was used in practical applications. 

In [ ]:
import numpy as np

Task: create a normalized form of the following data set (accessed through UCI Machine Learning Repository) whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

In [ ]:
# Load the data 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
data = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [ ]:
# Find the maximum and minimum values of data and print them: Smax and Smin
Smax = np.max(data)
Smin = np.min(data)
print(Smax, Smin)

7.9 4.3


In [ ]:
# Use (x - Smin)/(Smax - Smin) to normalize the data 
data_preprocessed = (data - Smin)/(Smax-Smin)
print(data_preprocessed)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

After writing your own code, we like to confirm that built-in functions in Scikit-Learn provide identical results. There are at least two techniques for normalizing the data using *sklearn.preprocessing*.

In [ ]:
# Technique 1: using minmax_scale 
from sklearn.preprocessing import minmax_scale
data_preprocessed2 = minmax_scale(data)
print(data_preprocessed2)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

In [ ]:
# Technique 2: using the``Transformer`` API MinMaxScaler 
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
data_preprocessed3 = scaler.fit_transform(data)

You probably got an error message. Please read this message and see how you can fix it. 
It looks like this error has to do something with the shape of *data* (1D vs 2D).
Please reshape *data* and make sure that the final normalized version has the same shape as *data_preprocessed* above. 

In [ ]:
# Technique 2: using the``Transformer`` API MinMaxScaler 
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
reshaped=np.reshape(data, (25, 6))
data_preprocessed3 = scaler.fit_transform(reshaped)
print(data_preprocessed3)

[[0.25925926 0.20689655 0.09090909 0.         0.12903226 0.26470588]
 [0.07407407 0.24137931 0.         0.09677419 0.25806452 0.08823529]
 [0.14814815 0.         0.42424242 0.35483871 0.25806452 0.17647059]
 [0.48148148 0.27586207 0.3030303  0.16129032 0.         0.17647059]
 [0.14814815 0.24137931 0.18181818 0.19354839 0.19354839 0.05882353]
 [0.14814815 0.37931034 0.24242424 0.29032258 0.09677419 0.14705882]
 [0.40740741 0.20689655 0.         0.16129032 0.12903226 0.        ]
 [0.         0.24137931 0.21212121 0.06451613 0.16129032 0.02941176]
 [0.33333333 0.24137931 0.78787879 0.58064516 0.74193548 0.29411765]
 [0.77777778 0.48275862 0.57575758 0.09677419 0.64516129 0.20588235]
 [0.22222222 0.55172414 0.48484848 0.48387097 0.32258065 0.64705882]
 [0.44444444 0.51724138 0.54545455 0.32258065 0.41935484 0.47058824]
 [0.7037037  0.62068966 0.60606061 0.64516129 0.70967742 0.64705882]
 [0.59259259 0.48275862 0.33333333 0.29032258 0.38709677 0.44117647]
 [0.37037037 0.5862069  0.6969697 